/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedFeesRouteImport } from './routes/_authenticated.fees'
import { Route as AuthenticatedMaintenanceRouteImport } from './routes/_authenticated.maintenance'
import { Route as AuthenticatedMyChildRouteImport } from './routes/_authenticated.my-child'
import { Route as AuthenticatedMyRoomRouteImport } from './routes/_authenticated.my-room'
import { Route as AuthenticatedNoticesRouteImport } from './routes/_authenticated.notices'
import { Route as AuthenticatedRequestsRouteImport } from './routes/_authenticated.requests'
import { Route as AuthenticatedResidentsRouteImport } from './routes/_authenticated.residents'
import { Route as AuthenticatedRoomsRouteImport } from './routes/_authenticated.rooms'
import { Route as AuthenticatedSiteContentRouteImport } from './routes/_authenticated.site-content'
import { Route as AuthenticatedReceiptInvoiceIdRouteImport } from './routes/_authenticated.receipt.$invoiceId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeesRoute = AuthenticatedFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMaintenanceRoute =
  AuthenticatedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyChildRoute = AuthenticatedMyChildRouteImport.update({
  id: '/my-child',
  path: '/my-child',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyRoomRoute = AuthenticatedMyRoomRouteImport.update({
  id: '/my-room',
  path: '/my-room',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNoticesRoute = AuthenticatedNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRequestsRoute = AuthenticatedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResidentsRoute = AuthenticatedResidentsRouteImport.update({
  id: '/residents',
  path: '/residents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoomsRoute = AuthenticatedRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSiteContentRoute =
  AuthenticatedSiteContentRouteImport.update({
    id: '/site-content',
    path: '/site-content',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReceiptInvoiceIdRoute =
  AuthenticatedReceiptInvoiceIdRouteImport.update({
    id: '/receipt/$invoiceId',
    path: '/receipt/$invoiceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fees': typeof AuthenticatedFeesRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/my-child': typeof AuthenticatedMyChildRoute
  '/my-room': typeof AuthenticatedMyRoomRoute
  '/notices': typeof AuthenticatedNoticesRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/residents': typeof AuthenticatedResidentsRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/site-content': typeof AuthenticatedSiteContentRoute
  '/receipt/$invoiceId': typeof AuthenticatedReceiptInvoiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fees': typeof AuthenticatedFeesRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/my-child': typeof AuthenticatedMyChildRoute
  '/my-room': typeof AuthenticatedMyRoomRoute
  '/notices': typeof AuthenticatedNoticesRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/residents': typeof AuthenticatedResidentsRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/site-content': typeof AuthenticatedSiteContentRoute
  '/receipt/$invoiceId': typeof AuthenticatedReceiptInvoiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fees': typeof AuthenticatedFeesRoute
  '/_authenticated/maintenance': typeof AuthenticatedMaintenanceRoute
  '/_authenticated/my-child': typeof AuthenticatedMyChildRoute
  '/_authenticated/my-room': typeof AuthenticatedMyRoomRoute
  '/_authenticated/notices': typeof AuthenticatedNoticesRoute
  '/_authenticated/requests': typeof AuthenticatedRequestsRoute
  '/_authenticated/residents': typeof AuthenticatedResidentsRoute
  '/_authenticated/rooms': typeof AuthenticatedRoomsRoute
  '/_authenticated/site-content': typeof AuthenticatedSiteContentRoute
  '/_authenticated/receipt/$invoiceId': typeof AuthenticatedReceiptInvoiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/fees'
    | '/maintenance'
    | '/my-child'
    | '/my-room'
    | '/notices'
    | '/requests'
    | '/residents'
    | '/rooms'
    | '/site-content'
    | '/receipt/$invoiceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/fees'
    | '/maintenance'
    | '/my-child'
    | '/my-room'
    | '/notices'
    | '/requests'
    | '/residents'
    | '/rooms'
    | '/site-content'
    | '/receipt/$invoiceId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/fees'
    | '/_authenticated/maintenance'
    | '/_authenticated/my-child'
    | '/_authenticated/my-room'
    | '/_authenticated/notices'
    | '/_authenticated/requests'
    | '/_authenticated/residents'
    | '/_authenticated/rooms'
    | '/_authenticated/site-content'
    | '/_authenticated/receipt/$invoiceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fees': {
      id: '/_authenticated/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof AuthenticatedFeesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/maintenance': {
      id: '/_authenticated/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-child': {
      id: '/_authenticated/my-child'
      path: '/my-child'
      fullPath: '/my-child'
      preLoaderRoute: typeof AuthenticatedMyChildRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-room': {
      id: '/_authenticated/my-room'
      path: '/my-room'
      fullPath: '/my-room'
      preLoaderRoute: typeof AuthenticatedMyRoomRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notices': {
      id: '/_authenticated/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof AuthenticatedNoticesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/requests': {
      id: '/_authenticated/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/residents': {
      id: '/_authenticated/residents'
      path: '/residents'
      fullPath: '/residents'
      preLoaderRoute: typeof AuthenticatedResidentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rooms': {
      id: '/_authenticated/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthenticatedRoomsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/site-content': {
      id: '/_authenticated/site-content'
      path: '/site-content'
      fullPath: '/site-content'
      preLoaderRoute: typeof AuthenticatedSiteContentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/receipt/$invoiceId': {
      id: '/_authenticated/receipt/$invoiceId'
      path: '/receipt/$invoiceId'
      fullPath: '/receipt/$invoiceId'
      preLoaderRoute: typeof AuthenticatedReceiptInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFeesRoute: typeof AuthenticatedFeesRoute
  AuthenticatedMaintenanceRoute: typeof AuthenticatedMaintenanceRoute
  AuthenticatedMyChildRoute: typeof AuthenticatedMyChildRoute
  AuthenticatedMyRoomRoute: typeof AuthenticatedMyRoomRoute
  AuthenticatedNoticesRoute: typeof AuthenticatedNoticesRoute
  AuthenticatedRequestsRoute: typeof AuthenticatedRequestsRoute
  AuthenticatedResidentsRoute: typeof AuthenticatedResidentsRoute
  AuthenticatedRoomsRoute: typeof AuthenticatedRoomsRoute
  AuthenticatedSiteContentRoute: typeof AuthenticatedSiteContentRoute
  AuthenticatedReceiptInvoiceIdRoute: typeof AuthenticatedReceiptInvoiceIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFeesRoute: AuthenticatedFeesRoute,
  AuthenticatedMaintenanceRoute: AuthenticatedMaintenanceRoute,
  AuthenticatedMyChildRoute: AuthenticatedMyChildRoute,
  AuthenticatedMyRoomRoute: AuthenticatedMyRoomRoute,
  AuthenticatedNoticesRoute: AuthenticatedNoticesRoute,
  AuthenticatedRequestsRoute: AuthenticatedRequestsRoute,
  AuthenticatedResidentsRoute: AuthenticatedResidentsRoute,
  AuthenticatedRoomsRoute: AuthenticatedRoomsRoute,
  AuthenticatedSiteContentRoute: AuthenticatedSiteContentRoute,
  AuthenticatedReceiptInvoiceIdRoute: AuthenticatedReceiptInvoiceIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
